# ────────────────────────────────────────────────────────────────────────────
# Copy this file to YOUR_REPO/.github/workflows/main-push.yml
# Triggered on every push to main: runs CI then deploys to staging.
# ────────────────────────────────────────────────────────────────────────────
name: Main — CI + Deploy Staging

on:
  push:
    branches: [main]

concurrency:
  group: main-push
  cancel-in-progress: false   # never cancel a deploy mid-flight

jobs:
  ci:
    name: CI
    uses: YOUR_ORG/goship/.github/workflows/ci-pipeline.yml@main
    with:
      go-version: '1.23'
      binary-name: myapp
      main-package: './cmd/server'
      run-integration-tests: true
      postgres-enabled: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      INTEGRATION_ENV: ${{ secrets.INTEGRATION_ENV }}

  deploy-staging:
    name: Deploy → Staging
    needs: ci
    uses: YOUR_ORG/goship/.github/workflows/cd-pipeline.yml@main
    with:
      environment: staging
      image-name: ghcr.io/${{ github.repository }}
      dockerfile: Dockerfile
      platforms: linux/amd64
      run-migrations: true
      migration-tool: golang-migrate
      migrations-dir: migrations
      ssh-host: staging.example.com
      ssh-user: deploy
      compose-file-local: docker-compose.yml
      compose-file-remote: ~/app/docker-compose.yml
      service-name: api
      ssh-known-hosts: ${{ vars.STAGING_SSH_KNOWN_HOSTS }}
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
      DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
