# ────────────────────────────────────────────────────────────────────────────
# Copy this file to YOUR_REPO/.github/workflows/pr-checks.yml
# Replace "YOUR_ORG/goship" with your actual org/repo name.
# ────────────────────────────────────────────────────────────────────────────
name: PR Checks

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]

# Cancel in-flight runs for the same PR
concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: YOUR_ORG/goship/.github/workflows/ci-pipeline.yml@main
    with:
      go-version: '1.23'
      binary-name: myapp
      main-package: './cmd/server'
      test-packages: './...'
      coverage-threshold: 70
      upload-coverage: true
      run-integration-tests: true
      integration-test-packages: './tests/integration/...'
      integration-test-tags: integration
      postgres-enabled: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      INTEGRATION_ENV: ${{ secrets.INTEGRATION_ENV }}
