# ────────────────────────────────────────────────────────────────────────────
# Copy this file to YOUR_REPO/.github/workflows/release.yml
# Triggered when a semver tag is pushed (e.g. v1.2.3).
# Runs CI, creates a GitHub Release, then deploys to production.
# ────────────────────────────────────────────────────────────────────────────
name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'   # pre-releases: v1.0.0-rc.1

jobs:
  ci:
    name: CI
    uses: YOUR_ORG/go-pipelines/.github/workflows/ci-pipeline.yml@main
    with:
      go-version: '1.23'
      binary-name: myapp
      main-package: './cmd/server'
      run-integration-tests: true
      postgres-enabled: true
    secrets:
      INTEGRATION_ENV: ${{ secrets.INTEGRATION_ENV }}

  release:
    name: GitHub Release
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true

  deploy-production:
    name: Deploy → Production
    needs: [ci, release]
    uses: YOUR_ORG/go-pipelines/.github/workflows/cd-pipeline.yml@main
    with:
      environment: production
      image-name: ghcr.io/${{ github.repository }}
      image-tag: ${{ github.ref_name }}
      dockerfile: Dockerfile
      platforms: linux/amd64,linux/arm64
      run-migrations: true
      migration-tool: golang-migrate
      migrations-dir: migrations
      ssh-host: prod.example.com
      ssh-user: deploy
      compose-file-local: docker-compose.yml
      compose-file-remote: ~/app/docker-compose.yml
      service-name: api
      ssh-known-hosts: ${{ vars.PROD_SSH_KNOWN_HOSTS }}
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
      DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
